### ISSUE TITLE
La función `and` no pasa el test

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#1]
La función `and` de la práctica 1 debería comportarse de la siguiente manera:
```
> and False (error "Mal")
False
```
Sin embargo, tu versión da `error "Mal"`.
Así, no es la función pedida.

**Comment by walterLaborde** [comment]
Fidel, al igual que en la función "or" pensé que al cambiar los guiones bajos iba a funcionar diferente pero hice la prueba para que me mostrara el error.. y me da False. Honestamente no me doy cuenta qué modificar (además de los guiones bajos) para que no de el error que, al menos cuando hice la prueba, no me salta.

**Comment by fidel-ml** [comment]
Como discutimos en clase, pasa el test por una característica nueva de Haskell. El tema es que hace doble PM (porque hacés un pattern específico para cada uno de los dos argumentos en la primera ecuación), y si bien Haskell los evalúa de a uno, eso es accidental. Técnicamente vos le estás diciendo que querés que los evalúe a ambos. Entonces si no precisás doble PM (y en este caso no hace falta), la idea es no usarlo.
Para solucionarlo, mirá cómo arreglaste el `or` y hacelo igual.

**Comment by walterLaborde** [comment]
ah, me parece que lo entendí.... en la primera ecuación con poner True b = b me alcanza porque como el primer argumento es True, el que define es b... ahí lo volví a modificar.
