### ISSUE TITLE
Pr2: `cantQueTrabajanEn` tiene un caso innecesario

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#10]
Dado que es una función que se resuelve por subtareas, ¿para qué mirar casos particulares de los que ya se encarga la subtarea?

**Comment by walterLaborde** [comment]
ah, ahora lo veo.. el caso de  [] no es necesario porque ya se encarga la subtarea... ahí lo borro. 

pusheado
