### ISSUE TITLE
Pr2: la función `asignadosPorProyecto` recorre la empresa muchas veces

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#12]
Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by walterLaborde** [comment]
en esta estoy trabado... no me doy cuenta de cómo completar los puntos suspensivos.... y no usar subtareas, es decir:
```
asignadosPorProyecto :: Empresa -> [(Proyecto, Int)]
asignadosPorProyecto  e = ... (elPrimero(proyectos e) , ....)  ... asignadosPorProyecto e
```
no me doy cuenta cómo hacer para armar una lista con tuplas .. voy a seguir con el tp 3 un rato y despues lo vuelvo a encarar... si tenes alguna pista mas sin decirme la respuesta, mejor por ahora avanzo con el resto

**Comment by fidel-ml** [comment]
Es que estás tratando de hacer recursión sobre la empresa, y no sobre los proyectos... NO ES RAZONABLE hacer recursión sobre una estructura no recursiva...
Fijate de obtener los ROLES de la empresa, y hacer recursión sobre ellos, sacan los proyectos en los que participa cada uno para hacer la cuenta...

**Comment by walterLaborde** [comment]
corregido
