### ISSUE TITLE
Pr3: en `poner` tenés una forma sofisticada de "miedo al tipo algebraico"

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#13]
Estás haciendo un PM para desarmar algo que vas a armar inmediatamente, sin usar las partes para nada más.
¿Para qué?

**Comment by walterLaborde** [comment]
si, no me había dado cuenta y le estaba cambiando el color en vez de agregarselo.... ahí lo modifiqué para que me devuelva la celda original y luego el color agregado

**Comment by walterLaborde** [comment]
ah, espero haber entendido.. vos me decís que para qué abro la Celda si en realidad solo quiero agregarle un color a lo que recibo... espero que sea eso... ahí lo modifiqué
