### ISSUE TITLE
Pr3: `pasosHastaTesoro` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#14]
No estás contando pasos, ya que no cortás cuando encontrás un tesoro... (Si hay un tesoro sin caminar, deberías dar cero).

Además, dice que hay un tesoro en un mapa sin nada (Fin), pero eso no es cierto. La función es parcial (lo pide el enunciado).

**Comment by walterLaborde** [comment]
modifiqué la función según lo que hablamos ayer. ya la subí
