### ISSUE TITLE
Pr3: `alMenosNTesoros` trabaja de más

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#16]
Estás reemplazando una búsqueda por una totalización, y eso no es bueno. Lo vieron en InPr con la búsqueda del ancho de espadas: si tengo 10mil cartas, y el ancho está primero, si trato de contar los anchos tengo que mirar las 10mil cartas, pero puedo cortar apenas veo esa carta y no necesito mirarlas todas...

**Comment by walterLaborde** [comment]
modificada.... ahora voy sumando los tesoros que encuentro en los cofres. subida

**Comment by fidel-ml** [comment]
Estás restando de a uno... tanto cuando hay muchos tesoros (caso cofre) como en el caso donde no hay ninguno (caso nada).
Creo que te mezclaste cantidad de tesoros con cantidad de pasos... :(

**Comment by walterLaborde** [comment]
listo, acá pude ver que estaba restando de a uno en vez de restar los tesoros que ya había encontrado. subido.
