### ISSUE TITLE
Hay "miedo al booleano" en la función `or`

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#2]
En la función `or` estás haciendo una versión con pattern matching del "miedo al booleano".
Básicamente, preguntás si algo es `True` para devolver `True` y cuando no es `True` devolvés `False`. Está escondida debido al uso de guiones bajos sin pensar demasiado... :-D
Básicamente, es como si tuvieses `if b==True then True else False`, que es exactamente lo mismo que `b`.

**Comment by walterLaborde** [comment]
Listo Fidel, ahÍ lo corregí. Ya entendí que no tenía sentido preguntar si algo era True o False cuando se lo estaba preguntando, justamente, a True o False.
