### ISSUE TITLE
Pr3: `ramaMasLarga` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#24]
No usa recursión estructural. Y su auxiliar utiliza leaves... ???

**Comment by walterLaborde** [comment]
si, ahi utilice la recursion estructural pero, honestamente, no estoy seguro que el resultado sea el que yo me imaginaba... es decir, cuando me dice que devuelve los elementos de la rama mas larga tengo que devolver los "a" de un Tree a, no es cierto? y esos son los elementos que yo devolvia en el ejercicio de leaves... por eso utilice esa funcion (asi lo pense)... de todas formas estaba muy mal la "supuesta recursion" que no fue. ya subi la modificacion

**Comment by fidel-ml** [comment]
Siempre tratá de hacerte un ejemplo antes de mandarte a hacer código...
Ahora está mejor.
Sin embargo, te aviso que las correcciones de la práctica 3 no cuentan ya para la asistencia, porque están demasiado atrasadas. Igual me parece bien que las mires e intentes corregirlas, porque son importantes.
