### ISSUE TITLE
Pr2: los casos de `zipMaximos` no aparecen en un orden interesante

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#3]
El orden marca la forma en que lo pensás. Y así como está, salta de mirar el 2do parámetro a mirar el primero y luego a ambos. Sería mejor mirar primero el 1ero, y luego, cuando hace falta, el otro... (solamente basta con cambiar el orden de las ecuaciones... ;))

**Comment by walterLaborde** [comment]
si, tenés razón.. ya lo modifiqué.. lo pusheo en un rato.
