### ISSUE TITLE
Pr2: el primer caso de `mayoresA` es innecesario (Y te rompe la recursión estructural)

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#5]
No trates de pensar casos particulares ANTES de pensar la estructura general de la función. Eso SIEMPRE lleva a trabajo de más y muchas veces a errores diversos.

**Comment by walterLaborde** [comment]
Acá me doy cuenta que lo pensé de la siguiente manera: si el primer parámetro es cero... luego si el segundo parametro es []... y por último, si ninguno lo és... y desde ahí lo fui construyendo... pero no me dí cuenta que "mi tercer caso" contemplaba al primero. ya está modificado.

**Comment by fidel-ml** [comment]
Exacto. El código refleja de alguna manera la forma en que uno piensa... NO pienses casos particulares primero (es tratar de arrojarte por la ventana para llegar más rápido... :P)
