### ISSUE TITLE
Pr2: el primer caso de `promedioEdad` es innecesario

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#6]
Básicamente, está contemplado en el otro caso. ¿Para qué pensarlo separado? Es el doble de trabajo (Y como te dije antes, propenso a errores)

**Comment by walterLaborde** [comment]
si, ahora lo veo. corregido

**Comment by fidel-ml** [comment]
Es raro que diga `(p:ps)` y lo uses exactamente igual del otro lado. ¿Para que usar PM para deconstruir algo que vas a reconstruir inmediatamente sin cambios? Si lo que querés es evitar el caso `[]` es más fácil agregarlo aparte con un error...

**Comment by walterLaborde** [comment]
si, es cierto... la verdad no sé por qué lo hice así.. ya lo volví a corregir.

**Comment by fidel-ml** [comment]
Ahora tenés muchos paréntesis de más... Nunca pongas algo que está solo entre paréntesis...

**Comment by walterLaborde** [comment]
si, ahi lo corregi.. no se por que lo habia dejado asi.

**Comment by fidel-ml** [comment]
Lo sigo viendo con la misma cantidad...

**Comment by walterLaborde** [comment]
creo que hice el commit y no pushie... ya estoy en la calle, cuando llego hago el push
