### ISSUE TITLE
Pr2: la función `losQueGanan` no es correcta

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#7]
Estás comparando los de un tipo del primero solamente con los de ese tipo del segundo. Pero la idea es comprarlo con todos.
Y el if que usás suena bien feo...

**Comment by walterLaborde** [comment]
en este ejercicio no entiendo cómo sería la comparación.. es decir, si el entrenador 1 tiene 2 Pokemon de Tipo Agua y el entrenador 2 sólo 1, entonces le gana... así es como lo entendí el ejercicio porque me pide la cantidad. 
cómo debería compararlos? no termino de entenderlo...

**Comment by fidel-ml** [comment]
No trates de pensar cómo un Pokémon le gana a otro. Pensá que tenés 2 grupos de elementos, y necesitás los del 1er grupo que le ganan a TODOS los del 2do grupo. Para esto, ¿qué te conviene recorrer? No trates de solucionar TODO el problema de una, sino en dividir en subtareas...

**Comment by walterLaborde** [comment]
Ahí lo modifiqué... la verdad, no me quedó muy diferente de como estaba... y tiene un if... pero no me doy cuenta de cómo solucionarlo de otra forma.... mi estrategia fue:
1. verificar si el Tipo "t" que me dan por parámetro le gana a todos los del entrenador 2
2. si eso da true, me fijo cuántos de esos tiene entrenador 1 y devuelvo ese valor; caso contrario devuelvo 0

ya está pusheado

**Comment by fidel-ml** [comment]
El problema está en 1. NO tenés que usar el tipo para ver si le gana, porque un tipo NO LE GANA a nadie... Es un Pokémon de ese tipo el que le gana a otros. Y podría ser que ese Pokémon usase MÁS que solamente su tipo para ganarle, y a vos no debería afectarte.
Es justamente porque estás tratando de aprovechar lo que supuestamente sabés sobre la pelea que no te sale. Vos tenés que hacer que PELEEN POKÉMON y ver si gana a todos o no, no usar tipos para eso... Pero no pelean TODOS los Pokémon, sino solamente los del tipo que te dan.
A ver si con eso te sale...

**Comment by walterLaborde** [comment]
Hice una versión donde pelean los POKEMON pero no la puedo subir porque me da mal el resultado.... te comparto lo que hice y si no lo podes ver te lo consulto mañana en clase:

```
losQueLeGanan :: TipoDePokemon -> Entrenador -> Entrenador -> Int
losQueLeGanan t (ConsEntrenador _ ps1) (ConsEntrenador _ ps2) = cantPokeQueLeGanaATodos t ps1 ps2

cantPokeQueLeGanaATodos :: TipoDePokemon -> [Pokemon] -> [Pokemon] -> Int
cantPokeQueLeGanaATodos t ps1 ps2 = 
                      if(hayPokeTipo (pokeDeTipo t ps1) && leGananATodos (pokeDeTipo t ps1) ps2) 
                        then longitud (pokeDeTipo t ps1)
                        else 0

hayPokeTipo :: [Pokemon] -> Bool
hayPokeTipo [] = False
hayPokeTipo ps = True

leGananATodos :: [Pokemon] -> [Pokemon] -> Bool
leGananATodos []       _        = False
leGananATodos (p1:ps1) (p2:ps2) = superaA p1 p2 && leGananATodos ps1 ps2

pokeDeTipo :: TipoDePokemon -> [Pokemon] -> [Pokemon]
pokeDeTipo t []      = []
pokeDeTipo t (p:ps)  = singularSi p (esDeTipo t p) ++ pokeDeTipo t ps

esDeTipo :: TipoDePokemon -> Pokemon -> Bool
esDeTipo t p = t == tipo p 

singularSi :: a -> Bool -> [a]
singularSi x True  = [x]
singularSi x False = []

``` 

la función "leGananATodos" da falso cuando tendría que dar verdadero.

**Comment by fidel-ml** [comment]
Seguís mirando el tipo... Tu lógica está mal... Vos estás recorriendo para ver si hay alguno, y después recorriendo para contar.

Tenés que pensar en recorrer la primera lista por recursión estructural y CONTAR los que cumplan la condición. Y NADA MÁS.
Para eso, chequeás si el pokémon es del tipo esperado y también si le gana a todos los de la otra lista.

**Comment by fidel-ml** [comment]
Muchísimo mejor. Fijate que la pregunta si p tiene tipo t la estás haciendo CADA VEZ que pelea, en lugar de preguntarla una sola vez antes de dejarlo pelear... ¿Si ya sabés que no es de tipo, para qué volvérselo a preguntar cada vez? ;)

**Comment by walterLaborde** [comment]
ok, se me ocurrió hacer una subtarea en la primera función en la que filtro los poke del tipo que me piden del Entrenador 1 y desde ahí sólo me manejo con pokemones. subido
