### ISSUE TITLE
Pr2: faltan todos los ejercicios de Proyectos...

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#8]
Eso.

**Comment by walterLaborde** [comment]
si, tengo subido hasta el primero inclusive... me faltan los tres siguientes

**Comment by walterLaborde** [comment]
estoy en eso

**Comment by fidel-ml** [comment]
Meta garra. :-D

**Comment by walterLaborde** [comment]
ya los subí todos.. ahora estoy viendo los issues de los anteriores

**Comment by walterLaborde** [comment]
por las dudas vuelvo a comentar.. ya estan todos subidos
