### ISSUE TITLE
Pr 2: en `sinRepetidos` estás mirando la pertenencia contra una lista más larga de lo necesaria

### ISSUE THREAD

**Issue by fidel-ml** [walterLaborde/EstrD22s1#9]
Al usar `xs` en lugar de `sinRepetidos xs` en la condición, mirás más veces de las necesarias.
Esto es en general para cuando querés remover duplicados...

Esto es lo que charlamos en clase... ;)

**Comment by walterLaborde** [comment]
si, me dí cuenta cuando lo dijiste en clase.. ya subí la corrección
